version: '3.8'

networks:
  laranet:
    driver: bridge

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: willfakri/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: willfakri/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"