version: '3.8'

networks:
  node-network:
    driver: bridge

services:
  app:
    build: 
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - /node/usr/src/app
    tty: true
    ports:
      - "3000:3000"
      
  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQLDATABASE=nodedb      
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network