version: '3.8'

networks:
  laranet:
    driver: bridge

services:
  laravel:
    image: willfakri/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: willfakri/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"